import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {seed} from '@/lib/model';
import {z} from 'zod';
export const dynamic='force-dynamic';
const entry=z.object({id:z.string().min(1).max(160),kind:z.enum(['task','habit','check','block','category','note','session']),title:z.string().max(3000).optional(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),category:z.string().max(160).optional(),done:z.boolean().optional(),start:z.number().min(0).max(23.5).optional(),end:z.number().min(0.5).max(24).optional(),days:z.array(z.number().int().min(0).max(6)).max(7).optional(),color:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),minutes:z.number().min(0).max(1440).optional(),deleted:z.boolean().optional(),version:z.number().int().min(0).optional()});
const db=()=> (env as unknown as {DB:D1Database}).DB;
export async function GET(){try{const user=await getChatGPTUser();if(!user)return Response.json({error:'Please sign in to sync.'},{status:401});const database=db();await database.batch(seed.map(e=>database.prepare('INSERT OR IGNORE INTO records(owner,id,body,version) VALUES(?,?,?,1)').bind(user.userId,e.id,JSON.stringify(e))));const {results}=await database.prepare('SELECT body,version FROM records WHERE owner=?').bind(user.userId).all<{body:string,version:number}>();return Response.json({owner:user.userId,records:results.map(r=>({...JSON.parse(r.body),version:r.version}))},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Sync is temporarily unavailable. Your changes remain on this device.'},{status:503});}}
export async function POST(request:Request){try{if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'Please sign in to sync.'},{status:401});if(Number(request.headers.get('content-length')||0)>300000)return new Response(null,{status:413});const input=z.object({owner:z.string(),changes:z.array(entry).max(100)}).safeParse(await request.json());if(!input.success)return Response.json({error:'Invalid change'},{status:400});if(input.data.owner!==user.userId)return Response.json({error:'Account changed. Reopen the app.'},{status:403});for(const e of input.data.changes){if(e.kind==='block'&&(!(e.start!<e.end!)||!e.days?.length))return Response.json({error:'Invalid time block'},{status:400});}
const database=db();const result=await database.batch(input.data.changes.map(e=>database.prepare('INSERT INTO records(owner,id,body,version) VALUES(?,?,?,1) ON CONFLICT(owner,id) DO UPDATE SET body=excluded.body,version=records.version+1 WHERE records.version=?').bind(user.userId,e.id,JSON.stringify(e),e.version||0)));const conflicts=input.data.changes.filter((_,i)=>result[i].meta.changes===0).map(e=>e.id);return Response.json({conflicts});}catch(e){console.error(e);return Response.json({error:'Unable to sync. Your changes are safe on this device.'},{status:503});}}
