'use client';
import {useEffect,useState} from 'react';
import {Bell,BellOff} from 'lucide-react';
import {toast} from 'sonner';
import {apiFetch} from '@/lib/supabase';
const zones=['Asia/Karachi','Asia/Kolkata','Asia/Dubai','Asia/Dhaka','Asia/Singapore','Asia/Tokyo','Europe/London','Europe/Paris','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Australia/Sydney','UTC'];
export default function Reminders(){
 const [timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Karachi'),[enabled,setEnabled]=useState(false),[device,setDevice]=useState(false),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[supported,setSupported]=useState(false);
 useEffect(()=>{setSupported('PushManager' in window&&'Notification' in window&&'serviceWorker' in navigator);apiFetch('preferences').then(async r=>{if(!r.ok)throw new Error('Could not load reminder settings');const value=await r.json() as {timezone?:string;reminder_enabled?:boolean;vapidPublicKey?:string};setTimezone(value.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone);setEnabled(!!value.reminder_enabled);setKey(value.vapidPublicKey||'');}).catch(e=>toast.error(e.message));navigator.serviceWorker?.getRegistration().then(async r=>setDevice(!!await r?.pushManager.getSubscription()));},[]);
 async function settings(value:boolean){const r=await apiFetch('preferences',{method:'POST',body:JSON.stringify({timezone,reminder_enabled:value})});if(!r.ok)throw new Error('Could not save reminders');setEnabled(value);}
 async function enable(){setBusy(true);try{if(!key)throw new Error('Reminder setup is still loading. Try again.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications in your browser settings to enable reminders.');await navigator.serviceWorker.register('/sw.js');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const raw=key.replace(/-/g,'+').replace(/_/g,'/');const bytes=Uint8Array.from(atob(raw+'='.repeat((4-raw.length%4)%4)),c=>c.charCodeAt(0));sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});}const r=await apiFetch('push',{method:'POST',body:JSON.stringify(sub.toJSON())});if(!r.ok)throw new Error('Could not register this device');await settings(true);setDevice(true);toast.success('Midnight reminders enabled for this device');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.getRegistration(),sub=await reg?.pushManager.getSubscription();if(sub){const r=await apiFetch('push',{method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})});if(!r.ok)throw new Error('Connect to the internet to disable this device');await sub.unsubscribe();}setDevice(false);toast.success('This device’s reminders are off');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <><h3>Midnight check-in</h3><p>At 12:00 AM, get a reminder if yesterday hasn’t been marked <strong>Day complete</strong>. Tap it to open yesterday’s page.</p><label className="timezone-label">Your time zone<select value={timezone} onChange={e=>setTimezone(e.target.value)}>{Array.from(new Set([timezone,...zones])).map(z=><option key={z} value={z}>{z.replaceAll('_',' ')}</option>)}</select></label><div className="reminder-buttons"><button className="outline" disabled={busy} onClick={()=>settings(enabled).then(()=>toast.success('Time zone saved')).catch(e=>toast.error(e.message))}>Save time zone</button>{device?<button className="outline" disabled={busy} onClick={disable}><BellOff size={17}/>Turn off this device</button>:<button className="primary" disabled={busy||!supported} onClick={enable}><Bell size={17}/>{busy?'Enabling…':'Enable reminders'}</button>}</div><p className="reminder-note">{device?'This device is registered. ':''}On iPhone, install to your Home Screen first. Delivery depends on your device, internet connection, and notification settings. Offline day completions must sync before midnight.</p></>;
}

