'use client';
import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import Reminders from './reminders';
import {Activity,LayoutDashboard,CalendarDays,CheckCheck,ChartNoAxesCombined,Settings,Plus,ChevronLeft,ChevronRight,ArrowUpRight,CloudCheck,Timer,Play,Pause,RotateCcw,Download,Trash2,Flame,Leaf,Menu,Check,Sun,BookOpen} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
import {Entry,dateKey,timeLabel} from '@/lib/model';
import {useTracker} from '@/lib/use-tracker';
function NavButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){const {setOpenMobile}=useSidebar();return <SidebarMenuButton isActive={active} onClick={()=>{onClick();setOpenMobile(false);}}>{children}</SidebarMenuButton>;}
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const nav=[{name:'My day',icon:LayoutDashboard},{name:'Weekly rhythm',icon:CalendarDays},{name:'Habits',icon:CheckCheck},{name:'Insights',icon:ChartNoAxesCombined}];
function uid(){
 if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();
 return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&0x3|0x8)).toString(16);});
}

export default function Tracker({user,onSignOut}:{user:User;onSignOut:()=>Promise<void>}){
 const data=useTracker(user.id),{records,save,ready,status,clearPending,pendingCount}=data;
 const [view,setView]=useState('My day'),[date,setDate]=useState(dateKey()),[now,setNow]=useState(new Date()),[editing,setEditing]=useState<Entry|null>(null),[filter,setFilter]=useState('all'),[install,setInstall]=useState<any>(null),[installHelp,setInstallHelp]=useState(false),[seconds,setSeconds]=useState(1500),[running,setRunning]=useState(false),[endAt,setEndAt]=useState(0),[focusMinutes,setFocusMinutes]=useState(25),[note,setNote]=useState('');
 const selected=new Date(date+'T12:00:00'),day=(selected.getDay()+6)%7,cats=records.filter(e=>e.kind==='category'),tasks=records.filter(e=>e.kind==='task'&&e.date===date),habits=records.filter(e=>e.kind==='habit'),blocks=records.filter(e=>e.kind==='block'),sessions=records.filter(e=>e.kind==='session'&&e.date===date),todayBlocks=blocks.filter(e=>e.days?.includes(day)).sort((a,b)=>a.start!-b.start!),completed=tasks.filter(e=>e.done).length;
 const category=(id?:string)=>cats.find(c=>c.id===id)||cats[0];
 const checked=(id:string,d=date)=>records.some(e=>e.id===`check:${id}:${d}`&&e.done);
 const habitCount=habits.filter(e=>checked(e.id)).length,total=tasks.length+habits.length,done=completed+habitCount,percent=total?Math.round(done/total*100):0;
 const current=date===dateKey(now)?todayBlocks.find(b=>now.getHours()+now.getMinutes()/60>=b.start!&&now.getHours()+now.getMinutes()/60<b.end!):undefined;
 const week=Array.from({length:7},(_,i)=>{const d=new Date(selected);d.setDate(d.getDate()-day+i);return d;});
 function shift(n:number){const d=new Date(selected);d.setDate(d.getDate()+n);setDate(dateKey(d));}
 function edit(kind:Entry['kind']){setEditing({id:uid(),kind,title:'',category:'green',date,start:9,end:10,days:[day],color:'#388960'});}
 function checkHabit(h:Entry,d=date){save({id:`check:${h.id}:${d}`,kind:'check',category:h.id,date:d,done:!checked(h.id,d)});}
 function streak(h:Entry){let n=0,d=new Date(now);if(!checked(h.id,dateKey(d)))d.setDate(d.getDate()-1);for(let i=0;i<3660&&checked(h.id,dateKey(d));i++){n++;d.setDate(d.getDate()-1);}return n;}
 useEffect(()=>{const requestedDate=new URLSearchParams(location.search).get('date');if(requestedDate&&/^\d{4}-\d{2}-\d{2}$/.test(requestedDate))setDate(requestedDate);const t=setInterval(()=>setNow(new Date()),1000);const listener=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',listener);if(process.env.NODE_ENV==='production')navigator.serviceWorker?.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{const urls=performance.getEntriesByType('resource').map(e=>e.name).filter(u=>u.startsWith(location.origin)&&/\.(js|css|woff2)(\?|$)/.test(u));reg.active?.postMessage({type:'CACHE_ASSETS',urls});}).catch(()=>{});return()=>{clearInterval(t);window.removeEventListener('beforeinstallprompt',listener);};},[]);
 useEffect(()=>{if(!running)return;const left=Math.max(0,Math.ceil((endAt-Date.now())/1000));setSeconds(left);if(!left){setRunning(false);save({id:uid(),kind:'session',date:dateKey(),minutes:focusMinutes,title:'Focus session'});toast.success('Focus session complete. Take a little break.');}},[now,running,endAt]);
 useEffect(()=>{setNote(records.find(e=>e.id===`note:${date}`)?.title||'');},[date,records.find(e=>e.id===`note:${date}`)?.title]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'show_tracker_view',description:'Open a tracker view without changing saved data.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['My day','Weekly rhythm','Habits','Insights','Settings']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!['My day','Weekly rhythm','Habits','Insights','Settings'].includes(input?.view))throw new Error('Invalid view');setView(input.view);return {view:input.view};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const catPicker=(value:string,onChange:(v:string)=>void)=><Select value={value} onValueChange={onChange}><SelectTrigger className="select-control"><SelectValue/></SelectTrigger><SelectContent>{cats.map(c=><SelectItem key={c.id} value={c.id}>{c.title}</SelectItem>)}</SelectContent></Select>;
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),records:data.allRecords},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`rhythm-${dateKey()}.json`;a.click();URL.revokeObjectURL(url);}
 function taskRow(t:Entry){const c=category(t.category);return <div className={'task-row '+(t.done?'done':'')} key={t.id}><Checkbox aria-label={`Complete ${t.title}`} checked={!!t.done} disabled={!ready} onCheckedChange={v=>save({...t,done:!!v})}/><button className="task-title" onClick={()=>setEditing(t)}>{t.title}</button><span className="pill" style={{color:c?.color,background:c?.color+'14'}}>{c?.title}</span></div>;}
 return <SidebarProvider><Sidebar className="main-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-icon"><Activity size={25}/></span>rhythm<span className="brand-period">.</span></a><div className="workspace-label">YOUR PERSONAL SPACE</div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.name}><NavButton active={view===n.name} onClick={()=>setView(n.name)}><n.icon size={20}/><span>{n.name}</span>{n.name==='My day'&&<span className="nav-count">{tasks.length-completed}</span>}</NavButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-separator"/><div className="workspace-label">YOUR CATEGORIES</div><div className="sidebar-categories">{cats.map(c=><button key={c.id} onClick={()=>setEditing(c)}><span style={{background:c.color}}/>{c.title}</button>)}</div><button className="add-category" onClick={()=>edit('category')}><Plus size={16}/>Add category</button></SidebarContent><SidebarFooter><div className="sidebar-quote"><Leaf size={21}/><p>Small steps.<br/>A rhythm that lasts.</p><span>Make room for what matters.</span></div><button className={'settings-link '+(view==='Settings'?'selected':'')} onClick={()=>setView('Settings')}><Settings size={19}/>Settings & devices</button><div className="profile"><div className="avatar">{(user.user_metadata?.full_name||user.email||"U")[0].toUpperCase()}</div><div><strong>{user.user_metadata?.full_name||"My workspace"}</strong><small>Personal • Private</small></div></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>My workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><button className="sync-button" onClick={()=>data.sync()}><CloudCheck size={17}/><span>{status}</span></button></header>
 <div className="page"><div className="page-heading"><div><div className="eyebrow"><Sun size={15}/>{selected.toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</div><h1>{view==='My day'?'Make today count.':view==='Weekly rhythm'?'Find your rhythm.':view==='Habits'?'Consistency starts small.':view==='Insights'?'See how far you’ve come.':'Your space, your way.'}</h1><p>{view==='My day'?'A little intention. A little progress. A day that feels like you.':view==='Weekly rhythm'?'Give every part of your day a place.':view==='Habits'?'Build the little routines that make a big difference.':view==='Insights'?'An honest look at your progress, one day at a time.':'Keep your rhythm with you, wherever you are.'}</p></div><button className="primary" disabled={!ready} onClick={()=>edit(view==='Weekly rhythm'?'block':view==='Habits'?'habit':'task')}><Plus size={18}/>{view==='Weekly rhythm'?'Add time block':view==='Habits'?'New habit':'New task'}</button></div>
 {data.conflicts.length>0&&<div className="notice">{data.conflicts.map(id=><div key={id}>“{records.find(r=>r.id===id)?.title||'Time block'}” changed on another device. <button onClick={()=>data.resolve(id,true)}>Keep this version</button><button onClick={()=>data.resolve(id,false)}>Use cloud version</button></div>)}</div>}
 {!ready&&<div className="notice">Connecting to your private workspace. <button onClick={()=>data.sync()}>Try again</button>{status.includes('Sign in')&&<button onClick={()=>onSignOut().catch(e=>toast.error(e.message))}>Sign in</button>}</div>}
 {view!=='Settings'&&<div className="date-strip"><div className="date-nav"><button aria-label="Previous day" onClick={()=>shift(-1)}><ChevronLeft size={17}/></button><button onClick={()=>setDate(dateKey())}>Today</button><button aria-label="Next day" onClick={()=>shift(1)}><ChevronRight size={17}/></button></div><div className="week-days">{week.map(d=><button className={dateKey(d)===date?'active':''} key={dateKey(d)} onClick={()=>setDate(dateKey(d))}><span>{days[(d.getDay()+6)%7]}</span><strong>{d.getDate()}</strong>{dateKey(d)===dateKey(now)&&<i/>}</button>)}</div><label className="date-input"><CalendarDays size={17}/><input aria-label="Choose date" type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label></div>}
 {view==='My day'&&<><div className="day-completion"><div><strong>{records.some(r=>r.id==='day:'+date&&r.done)?'Day complete. Nicely done.':'Have you captured your day?'}</strong><p>Finish your entries, then close the day to skip the midnight reminder.</p></div><button className="outline" disabled={!ready||date>dateKey(now)} onClick={()=>save({id:'day:'+date,kind:'day',date,done:!records.some(r=>r.id==='day:'+date&&r.done)})}><CheckCheck size={17}/>{records.some(r=>r.id==='day:'+date&&r.done)?'Reopen day':'Day complete'}</button></div><div className="stats"><div className="stat"><div className="stat-label">Daily progress <span className="stat-icon green"><CheckCheck size={19}/></span></div><div className="stat-value">{percent}<small>%</small><span>{done} of {total} completed</span></div><Progress value={percent} className="daily-progress"/></div><div className="stat"><div className="stat-label">Focus time <span className="stat-icon orange"><Timer size={19}/></span></div><div className="stat-value">{sessions.reduce((s,e)=>s+(e.minutes||0),0)}<small>min</small></div><p>Space for your most meaningful work</p></div><div className="stat"><div className="stat-label">Habit momentum <span className="stat-icon purple"><Flame size={19}/></span></div><div className="stat-value">{Math.max(0,...habits.map(streak))}<small>days</small></div><p>Your longest active habit streak</p></div></div>
 <div className="dashboard-grid"><div className="left-stack"><section className="card tasks-card"><div className="section-heading"><h2>Today’s tasks <span className="count">{tasks.length}</span></h2><button className="text-link" onClick={()=>edit('task')}><Plus size={16}/>Add task</button></div><div className="task-filters">{['all','open','done'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='all'?'All tasks':f==='open'?'To do':'Completed'}<span>{f==='all'?tasks.length:f==='open'?tasks.length-completed:completed}</span></button>)}</div>{tasks.filter(t=>filter==='all'||(filter==='done'?t.done:!t.done)).map(taskRow)}{!tasks.length&&<div className="empty"><div className="empty-icon"><CheckCheck/></div><h3>A fresh page for your day</h3><p>What would make today feel worthwhile?</p><button className="outline" onClick={()=>edit('task')}>Add your first task <Plus size={16}/></button></div>}{!!tasks.length&&<button className="add-task-line" onClick={()=>edit('task')}><Plus size={18}/>Add another task</button>}</section>
 <section className="card"><div className="section-heading"><h2>Little habits, big changes</h2><button className="text-link" onClick={()=>setView('Habits')}>View all <ArrowUpRight size={16}/></button></div><div className="habits-today">{habits.map(h=><div className={'habit-today '+(checked(h.id)?'checked':'')} key={h.id}><span className="habit-icon" style={{color:category(h.category)?.color,background:category(h.category)?.color+'16'}}><Leaf size={20}/></span><div><button onClick={()=>setEditing(h)}>{h.title}</button><small><Flame size={12}/>{streak(h)} day streak</small></div><Checkbox aria-label={`Complete habit ${h.title}`} checked={checked(h.id)} disabled={!ready} onCheckedChange={()=>checkHabit(h)}/></div>)}</div></section>
 <section className="card reflection"><div className="section-heading"><h2>A moment to reflect</h2><BookOpen size={18}/></div><textarea aria-label="Daily reflection" placeholder="What went well? What’s on your mind?" maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/><div><small>Just for you. A little space to clear your head.</small><button className="text-link" disabled={!ready} onClick={()=>{if(save({id:`note:${date}`,kind:'note',date,title:note}))toast.success('Reflection saved');}}>Save reflection</button></div></section></div>
 <div className="right-stack"><section className="focus-card"><div className="focus-top"><span><span className="live-dot"/>{current?'IN YOUR RHYTHM':'MAKE SOME SPACE'}</span><Timer size={19}/></div><h2>{current?(current.title||category(current.category)?.title):'Time to focus'}</h2><p>{current?`${timeLabel(current.start!)} – ${timeLabel(current.end!)} · ${category(current.category)?.title}`:'One thing at a time. You’ve got this.'}</p><div className="timer-digits">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</div><div className="focus-buttons"><button disabled={!ready} onClick={()=>{if(running)setRunning(false);else{setEndAt(Date.now()+seconds*1000);setRunning(true);}}}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause focus':'Start focus'}</button><button aria-label="Reset timer" onClick={()=>{setRunning(false);setSeconds(focusMinutes*60);}}><RotateCcw size={17}/></button></div><div className="focus-presets">{[25,50].map(n=><button className={focusMinutes===n?'active':''} disabled={running} key={n} onClick={()=>{setFocusMinutes(n);setSeconds(n*60);}}>{n} min</button>)}<span>Stay present. Keep going.</span></div></section>
 <section className="card timeline"><div className="section-heading"><h2>Your daily rhythm</h2><button aria-label="Open weekly schedule" onClick={()=>setView('Weekly rhythm')}><ArrowUpRight size={18}/></button></div><div className="timeline-sub">A little structure, a lot of possibility.</div>{todayBlocks.map(b=>{const c=category(b.category);return <button className={'timeline-row '+(b.id===current?.id?'current':'')} key={b.id} onClick={()=>setEditing(b)}><span className="timeline-time">{timeLabel(b.start!)}</span><span className="timeline-track" style={{color:c?.color}}><i/></span><span className="timeline-info" style={{borderColor:c?.color,background:c?.color+'10'}}><strong>{b.title||c?.title}</strong><small>{timeLabel(b.start!)} – {timeLabel(b.end!)}{b.id===current?.id?' · Now':''}</small></span></button>})}<button className="week-link" onClick={()=>setView('Weekly rhythm')}>View weekly schedule <ArrowUpRight size={15}/></button></section></div></div></>}
 {view==='Weekly rhythm'&&<section className="card schedule-card"><div className="section-heading"><div><h2>Your weekly template</h2><p>Repeats every week. Tap a block to adjust your routine.</p></div><span className="subtle">{blocks.reduce((s,b)=>s+(b.end!-b.start!)*(b.days?.length||0),0)} planned hours / week</span></div><div className="legend">{cats.map(c=><button key={c.id} onClick={()=>setEditing(c)}><i style={{background:c.color}}/>{c.title}</button>)}</div><div className="schedule-scroll"><div className="schedule"><div className="hour-labels">{Array.from({length:25},(_,i)=><span key={i} style={{top:44+i*44}}>{timeLabel(i)}</span>)}</div>{days.map((d,i)=><div className={'day-column '+(i===day?'selected-day':'')} key={d}><div className="day-title">{d}<span>{week[i].getDate()}</span></div><div className="day-grid">{Array.from({length:24},(_,h)=><button className="hour-cell" aria-label={`Add block ${d} ${timeLabel(h)}`} key={h} onClick={()=>setEditing({id:uid(),kind:'block',title:'',category:'green',start:h,end:h+1,days:[i]})}/>)}{blocks.filter(b=>b.days?.includes(i)).map(b=>{const c=category(b.category);return <button key={b.id} className="schedule-block" style={{top:b.start!*44,height:(b.end!-b.start!)*44-3,color:c?.color,background:c?.color+'20',borderColor:c?.color}} onClick={()=>setEditing(b)}><strong>{b.title||c?.title}</strong>{(b.end!-b.start!)>=1.5&&<span>{timeLabel(b.start!)} – {timeLabel(b.end!)}</span>}</button>})}</div></div>)}</div></div></section>}
 {view==='Habits'&&<section className="card"><div className="section-heading"><h2>Your consistency journal</h2><span className="subtle">{week[0].toLocaleDateString('en',{month:'short',day:'numeric'})} – {week[6].toLocaleDateString('en',{month:'short',day:'numeric'})}</span></div><div className="habit-grid-wrap"><div className="habit-grid"><div className="habit-grid-header"><span>DAILY HABIT</span>{week.map((d,i)=><span key={i}>{days[i]}<b>{d.getDate()}</b></span>)}<span>STREAK</span></div>{habits.map(h=><div className="habit-grid-row" key={h.id}><button onClick={()=>setEditing(h)}><i style={{background:category(h.category)?.color}}/>{h.title}</button>{week.map(d=><div key={dateKey(d)}><Checkbox aria-label={`${h.title} on ${dateKey(d)}`} disabled={!ready||dateKey(d)>dateKey(now)} checked={checked(h.id,dateKey(d))} onCheckedChange={()=>checkHabit(h,dateKey(d))}/></div>)}<span className="streak"><Flame size={15}/>{streak(h)}</span></div>)}</div></div><button className="add-task-line" onClick={()=>edit('habit')}><Plus size={18}/>Create a new daily habit</button></section>}
 {view==='Insights'&&<div className="insights"><section className="card"><div className="section-heading"><h2>The last 14 days</h2><span className="subtle">Completed tasks & habits</span></div><div className="bar-chart">{Array.from({length:14},(_,i)=>{const d=new Date(selected);d.setDate(d.getDate()-13+i);const key=dateKey(d),count=records.filter(e=>(e.kind==='task'||e.kind==='check')&&e.date===key&&e.done).length;const max=Math.max(1,...Array.from({length:14},(_,j)=>{const x=new Date(selected);x.setDate(x.getDate()-13+j);return records.filter(e=>(e.kind==='task'||e.kind==='check')&&e.date===dateKey(x)&&e.done).length;}));return <div key={key}><b>{count}</b><div style={{height:`${Math.max(2,count/max*160)}px`}}/><span>{d.getDate()}</span></div>})}</div><p className="chart-caption">Every completed action is a small win. Your chart grows with you.</p></section><section className="card"><div className="section-heading"><h2>Where your week goes</h2></div>{cats.map(c=>{const hours=blocks.filter(b=>b.category===c.id).reduce((s,b)=>s+(b.end!-b.start!)*(b.days?.length||0),0);return <div className="allocation" key={c.id}><div><span><i style={{background:c.color}}/>{c.title}</span><strong>{hours}h</strong></div><div className="allocation-track"><span style={{width:`${Math.min(100,hours/168*100)}%`,background:c.color}}/></div></div>})}</section></div>}
 {view==='Settings'&&<div className="settings-grid"><section className="card"><div className="section-heading"><h2>All your devices. One rhythm.</h2><CloudCheck size={23}/></div><p>Your private workspace follows the same signed-in account on your phone and laptop. Open this address on both devices.</p><div className="setting-status">{status}</div><div style={{display:'flex',gap:'8px',flexWrap:'wrap',margin:'10px 0'}}><button className="outline" onClick={()=>data.sync()}>Sync now <CloudCheck size={17}/></button>{pendingCount>0&&<button className="outline" style={{borderColor:'#bc5d66',color:'#bc5d66'}} onClick={clearPending}>Discard queued changes ({pendingCount})</button>}</div><hr/><h3>Install Rhythm</h3><p>Keep your tracker one tap away, with a dedicated app window and offline access after your first visit.</p><button className="primary" onClick={async()=>{if(install){await install.prompt();setInstall(null);}else setInstallHelp(true);}}><Download size={17}/>Install app</button><hr/><Reminders/><hr/><h3>Keep a copy</h3><p>Download your tasks, habits, reflections, and schedule as a JSON backup. This export contains readable personal data.</p><button className="outline" onClick={download}><Download size={17}/>Export all data</button><hr/><button className="outline" onClick={()=>onSignOut().catch(e=>toast.error(e.message))}>Sign out</button></section><section className="card"><div className="section-heading"><h2>Your color palette</h2><Plus className="clickable" onClick={()=>edit('category')}/></div><p>The names below are starting points for the colors in your sketch. Make them your own.</p>{cats.map(c=><button className="category-setting" onClick={()=>setEditing(c)} key={c.id}><i style={{background:c.color}}/><span>{c.title}</span><ChevronRight size={16}/></button>)}</section></div>}
 <footer className="page-footer"><span><Activity size={14}/> Find your rhythm, one day at a time.</span><button onClick={()=>setView('Settings')}><Download size={14}/>Get the app</button></footer></div></main>
 <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing(null)}><DialogContent className="editor"><DialogHeader><DialogTitle>{editing&&records.some(r=>r.id===editing.id)?'Edit':'New'} {editing?.kind==='block'?'time block':editing?.kind}</DialogTitle><DialogDescription>{editing?.kind==='block'?'Design a little space in your recurring week.':'Make it meaningful and keep it simple.'}</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();if(editing.kind==='block'){if(editing.start!>=editing.end!||!editing.days?.length){toast.error('Choose an end after the start and at least one day.');return;}if(blocks.some(b=>b.id!==editing.id&&b.days?.some(d=>editing.days?.includes(d))&&b.start!<editing.end!&&b.end!>editing.start!)){toast.error('This overlaps an existing block. Adjust or remove that block first.');return;}}if(save(editing)){setEditing(null);toast.success('Saved to your rhythm');}}}>
 <label>{editing.kind==='block'?'Label (optional)':'Name'}<input autoFocus required={editing.kind!=='block'} maxLength={160} value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder={editing.kind==='task'?'What would you like to do?':'Give it a name'}/></label>
 {editing.kind!=='category'&&<label>Category{catPicker(editing.category||'green',v=>setEditing({...editing,category:v}))}</label>}
 {editing.kind==='task'&&<label>Date<input type="date" required value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label>}
 {editing.kind==='category'&&<label>Color<input type="color" value={editing.color} onChange={e=>setEditing({...editing,color:e.target.value})}/></label>}
 {editing.kind==='block'&&<><div className="time-fields"><label>Start<Select value={String(editing.start)} onValueChange={v=>setEditing({...editing,start:Number(v)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:48},(_,i)=><SelectItem key={i} value={String(i/2)}>{timeLabel(i/2)}</SelectItem>)}</SelectContent></Select></label><label>End<Select value={String(editing.end)} onValueChange={v=>setEditing({...editing,end:Number(v)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:48},(_,i)=><SelectItem key={i} value={String((i+1)/2)}>{timeLabel((i+1)/2)}</SelectItem>)}</SelectContent></Select></label></div><label>Repeat on</label><div className="day-choices">{days.map((d,i)=><button type="button" aria-pressed={editing.days?.includes(i)} className={editing.days?.includes(i)?'active':''} key={d} onClick={()=>setEditing({...editing,days:editing.days?.includes(i)?editing.days.filter(n=>n!==i):[...editing.days||[],i]})}>{d}</button>)}</div></>}
 <div className="editor-actions">{records.some(r=>r.id===editing.id)&&editing.kind!=='category'&&<button type="button" className="delete-button" onClick={()=>{if(save({...editing,deleted:true})){const removed=editing;setEditing(null);toast('Removed',{action:{label:'Undo',onClick:()=>save({...removed,deleted:false})}});}}}><Trash2 size={16}/>Remove</button>}<button className="primary" disabled={!ready} type="submit">Save {editing.kind==='block'?'block':editing.kind}<Check size={16}/></button></div></form>}</DialogContent></Dialog>
 <Dialog open={installHelp} onOpenChange={setInstallHelp}><DialogContent><DialogHeader><DialogTitle>Take your rhythm with you</DialogTitle><DialogDescription>Open this site in your phone’s main browser.</DialogDescription></DialogHeader><p><strong>iPhone / iPad:</strong> In Safari, tap Share, then Add to Home Screen.</p><p><strong>Android:</strong> In Chrome, open the menu, then Install app or Add to Home screen.</p><p><strong>Laptop:</strong> Look for the install icon in Chrome or Edge’s address bar.</p><p>Sign in with the same account on each device. Open the app online once before using it offline.</p></DialogContent></Dialog><Toaster richColors position="bottom-right"/></SidebarProvider>;
}


