import assert from 'node:assert/strict';
const base='http://localhost:5173';
const login=await fetch(base+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=login.headers.get('set-cookie').split(';')[0];
const headers={cookie,origin:base,'Content-Type':'application/json'};
const get=async()=>{const r=await fetch(base+'/api/sync',{headers});assert.equal(r.status,200);return r.json()};
const state=await get();
const id='qa-'+crypto.randomUUID();
const post=async(changes,extra={})=>{const r=await fetch(base+'/api/sync',{method:'POST',headers,body:JSON.stringify({owner:state.owner,changes,...extra})});return {status:r.status,body:await r.json()}};
const original={id,kind:'task',title:'Sync test',date:'2026-09-24',version:0};
assert.equal((await post([original])).status,200);
const remote=(await get()).records.find(e=>e.id===id);assert.equal(remote.version,1);
const results=await Promise.all([post([{...remote,title:'Device A'}]),post([{...remote,title:'Device B'}])]);
assert.equal(results.filter(r=>r.body.conflicts.length===0).length,1);
assert.equal(results.filter(r=>r.body.conflicts.includes(id)).length,1);
const latest=(await get()).records.find(e=>e.id===id);assert.equal(latest.version,2);
assert.equal((await post([{...latest,title:'Invalid account'}],{owner:'another-user'})).status,403);
assert.equal((await fetch(base+'/api/sync')).status,401);
assert.equal((await post([{...latest,kind:'block',start:12,end:11,days:[0]}])).status,400);
assert.equal((await post([{...latest,deleted:true}])).status,200);
assert.equal((await get()).records.find(e=>e.id===id).deleted,true);
console.log('PASS: create/read, concurrent edit conflict, account isolation, unauthenticated denial, invalid block denial, tombstone persistence.');
